safe: true
auto: false
exclude:
  - CNAME
  - README.md
url: "https://szen.in"
baseurl: /
markdown: redcarpet
pygments: true
lsi: false
permalink: /:year/:month/:title.html

title: "Molting Everyday"
author:
  name: "Snakevil Zen"
  email: "zsnakevil@gmail.com"
  github: snakevil
  twitter: snakevil
  facebook: snakevil.zen
  aboutme: snakevil.zen
  disqus: snakevil
excerpt: "\"MOLTING EVERYDAY\"，原『天天蜕皮的大蛇』，是 Snakevil Zen 的个人博客。聚焦于研发技术、互联网络和家用机游戏，也附带一些 GEEK 向的趣闻逸事。"
limit:
  index: 6
  tags: 36
  rss: 36
asset:
  url: "https://s.szen.in"
services:
  google:
    analytics:
      id: "UA-39915276-1"
      account: "szen.in"
    webmaster:
      site-verification: "bzzioVVz75GQoaHvBjZ1Ks6nl4pSSGlkpc-gfV4elYM"
