########################
# Jekyll Configuration #
########################

safe: true
auto: false
exclude:
  - CNAME
  - README.md
markdown: kramdown
pygments: true
lsi: false

#####################
# URL Configuration #
#####################

url: "https://szen.in" # DO NOT append any tailing slashes !
baseurl: /
permalink: /:year/:month/:title.html

######################
# Blog Configuration #
######################

title: "Molting Everyday"
author:
  name: "Snakevil Zen"
  email: "zsnakevil@gmail.com"
  twitter: snakevil
  aboutme: snakevil.zen
  google:
    plus: 114548287532214210712
excerpt: "MOLTING EVERYDAY，原『天天蜕皮的大蛇』，是 Snakevil Zen 的个人博客。聚焦于研发技术、互联网络和家用机游戏，也附带一些 GEEK 向的趣闻逸事。"
keywords:
  - "Architecture"
  - "架构"
  - "PHP"
  - "LNMP"
  - "GNU"
  - "Geek"
  - "奇客"
  - "TV Entertainment"
  - "电玩"
  - "Mac OS X"
limit:
  index: 5
  rss: 36
  recommendation: 6

#########################
# Widgets Configuration #
#########################

services:
  disqus:
    id: snakevil
  twitter:
    id: 323060021409746944
    limit: 5
    avatar: false
  google:
    analytics:
      id: "UA-39915276-1"
      mirror: "/s/j/ga.js"
